### ISSUE TITLE
Stream write not working on windows

### ISSUE THREAD

**Issue by serganus** [expressjs/morgan#101]
Hi my code is

`var HTTPlogger = require('morgan');`
`var FileStreamRotator = require('file-stream-rotator');`
`var logDev = __dirname + '/logs/Development';`

`var Dev_all = FileStreamRotator.getStream({
  date_format: 'YYYY-MM-DD',
  filename: logDev + '/%DATE%.json',
  frequency: 'daily',
  verbose: false
});`

`function DevJSON() {
var DATA = JSON.stringify({
        'status' :  ':status',
	    'method' :  ':method',
		'Remote-user': ':remote-user',
		'Remote-address': ':remote-addr',
		'URL': ':url',
		'HTTPversion': 'HTTP/:http-version',
		'Response-time': ':response-time[digits]',
		'date': ':date[web]',
		'Referrer': ':referrer'
         });
return DATA;
};`

`module.exports.developmentLOG = HTTPlogger(DevJSON(),{
  skip: function (req, res) { return res.statusCode < 399 },
  stream : {
  	write:function(Str){
  		Dev_all.write(Str),
  		console.log(Str);
  	}
  }
});`

in app.js :
`app.use(developmentLOG)`

Was not working on any OS?

**Comment by serganus** [comment]
Figured that middleware was set at the very in app.js :-). Closing it now. Although any suggestions to improve logging format, please feel free to comment.

**Comment by dougwilson** [comment]
Hi @serganus, I'm glad you were able to resolve your question :) Sorry it took me a while to get back to this issue. Really, as far as the suggestions go, I think it's pretty clever to log JSON this way, though there is always a possibility that some of those token may include a double quote (`"`), which would end up as a JSON syntax error when you try to read that entry (I guess just the `:referrer` token would be the most likely to have this issue).

The only way around this issue would be to use a `function` type of formatter instead of a string. Here is an example of how I would achieve what you have above (I'll just change `DevJSON` function to make it easier to read than the entire thing over again):
```js
function DevJSON() {
  return function (tokens, req, res) {
    return JSON.stringify({
      'status': tokens.status(req, res),
      'method': tokens.method(req, res),
      'Remote-user': tokens['remote-user'](req, res),
      'Remote-address': tokens['remote-addr'](req, res),
      'URL': tokens.url(req, res),
      'HTTPversion': 'HTTP/' + tokens['http-version'](req, res),
      'Response-time': tokens['response-time'](req, res, 'digits'),
      'date': tokens.date(req, res, 'web'),
      'Referrer': tokens.referrer(req, res)
    });
  };
};
```

I hope this helps you!

**Comment by serganus** [comment]
That helps a lot. Thanks!
