### ISSUE TITLE
Differences between the number of copyright holders

### ISSUE THREAD

**Issue by takuborn** [expressjs/morgan#104]
I posted same issue in csurf.
https://github.com/expressjs/csurf/issues/93

Is there no problem to use this package with MIT licese?

Because LICENSE has 2 copyright holders, but index.js has 4 holders.
```
Copyright(c) 2011 Sencha Inc.
Copyright(c) 2011 TJ Holowaychuk
```

Sorry for asking about trifles.

**Comment by dougwilson** [comment]
Hi! Unless you can point me to documentation from a law office or connect me to a lawyer to be sure, as far as I know, there is nothing in this package that nullifies the MIT license in here. The difference in the files is that in order to keep track, major copyrights are held in each source file with the copyrights of the packge itself held in the LICENSE file.

When a user contributes to an open source project that does not have a CLA (like this one), the copyright stays with the person (or company) that originally contributed the code, but they have implicitly granted the use of that code under the license terms of the project at the contribution time.

Note that I am not a lawyer, and as such, I cannot truly answer your question in any legal capacity. If you are unsure and are concerned, you may want to seek legal counsel.

I hope this helps!
