### ISSUE TITLE
Saving JSON log files to mongoDB, logged using morgan

### ISSUE THREAD

**Issue by serganus** [expressjs/morgan#110]
Hi, I was trying to pass all my logged JSON files to a document store such as MongoDB. 

Ref to logging toJSON : https://github.com/expressjs/morgan/issues/101

**Comment by dougwilson** [comment]
Hi @serganus, `morgan` is a line-based access logger, designed to be fed into a flat file on disk (or elsewhere). It does not easily allow for you to use storage that expects actual objects. You can of course "hack" it in order to do so. Here is an old example: https://github.com/expressjs/morgan/pull/44#issuecomment-62309400
