### ISSUE TITLE
remote_user empty

### ISSUE THREAD

**Issue by robotnic** [expressjs/morgan#131]
hi all

I'm using passport.js, sails.js, sails-hook-requestlogger-file and wso2.
:remote-user is not set in the logfile even if the user is logged in.

This would work for me:

```
morgan.token('remote-user', function getRemoteUserToken(req) {

  // return username
  return req.user
    ? req.user.email
    : undefined
})
```

But I don't know what's the best way to do this change.
Possibilities
* clone this repository and modify my copy
* overwrite the "remote-user" somehow - but how?

Any hints?

Bernhard

**Comment by dougwilson** [comment]
That is what you do--just paste that code in your app file.

**Comment by dougwilson** [comment]
Here is an example defining a token; if you define a token with a name that already exists, it replaces it, like you're trying to do: https://github.com/expressjs/morgan/blob/master/README.md#use-custom-token-formats

**Comment by robotnic** [comment]
Thanks for quick response.

I don't use morgan directly. It's used by this package:
https://github.com/maheshwarishivam/sails-hook-requestlogger-file/blob/master/index.js

Still lots of options to go.
* change sails-hook-requestlogger
* replace sails-hook-request logger by my own solution

**Comment by dougwilson** [comment]
So looking at that module (and the one it's forked from), it seems you'll need to get them to change something in order to customize this on them. They look almost like they are purposely trying to hide full access to the underlying `morgan` for some reason, with the biggest evidence to that is the fact that the fork you are using even needs to exist :)

I'm not sure that there is anything to actually do in this module, as we certainly support what you're trying to accomplish!
