### ISSUE TITLE
Maybe the better way to figure time

### ISSUE THREAD

**Issue by struCoder** [expressjs/morgan#147]
```javascript
    // some code...
    const reqTime =  process.hrtime()

    function reqFinished() {
      const resTime = process.hrtime();
      const ms = (resTime[0] - reqTime[0]) * 1e3 + (resTime[1] - reqTime[1]) * 1e-6
      // some code...
    }

    onHeaders(res, reqFinished)
```

Because, onFinished time was not figure, just figure req start and write HTTP headers time, so we don't need to figure time in onFinished function.

with this code, we don't need to req._startAt and res._startAt.

**Comment by dougwilson** [comment]
I'm not sure I understand. Can you elaborate? Or perhaps make a pull request to better demonstrate?

**Comment by danielgindi** [comment]
He's right.

I'm seeing weird "response" times, because it's not measuring the actual response time in some cases, like when streaming from a db.

What you are doing currently, is measure the time between the request coming in - and the response headers coming out.

But sometimes - generating the response is not an atomic operation that happens between the two.
Sometimes it's a heavy operation that you stream out incrementally. And you want to know how long did it take to finish writing out the response.

If it's a small JSON that you just write out immediately, then this won't affect the timings at all. But if it's a long streaming operation - the change will make sure that it reflects the actual time that the response took.

In my opinion this should be the default mode ("time until response finish"), possibly with an option to set  it to measure "time until response headers".

**Comment by dougwilson** [comment]
Hi @danielgindi yes, that is correct, and it's very clearly documented at the meaning of that token in the readme (https://github.com/expressjs/morgan#response-timedigits): 

> The time between the request coming into morgan and when the response headers are written, in milliseconds.

You're certainly welcome to make a pull request implementing the way you describe as another option as well 👍 @danielgindi

**Comment by dougwilson** [comment]
Anyway, coming back and read-reading @struCoder 's post, I understand what the purpose is now: the suggestion is to do the same thing already happening but without using the `_`-prefixed properties. The reason those properties are used @struCoder is so this module (and any custom token someone makes) can use them. I hope that helps!
