### ISSUE TITLE
Concurrency issue in cluster mode

### ISSUE THREAD

**Issue by kushubham9** [expressjs/morgan#167]
My application is running in PM2 cluster mode. I am using morgan to log input requests. However, I find that there are certain logs which are missing in the log file.

Is it possible that this is happening because of file concurrency issue? Anything I could do to fix this?

**Comment by dougwilson** [comment]
All this module is doing to write logs is calling either process.stdout.write() or calling your custom stream if you provided one. I don't think this module is doing anything special. Do you think is there a bug in the cluster module? Otherwise would you be able to either (a) pull request a fix or (b) provide full code and reproduction steps so we can reproduce?

**Comment by kushubham9** [comment]
I defined new upstream for each process. The stream issue is no more.
