### ISSUE TITLE
Test fails on Node.js 10

### ISSUE THREAD

**Issue by st-sloth** [expressjs/morgan#173]
Starting with 10.0.0 test `morgan() / formats / dev / should not color 1xx` fails with the exception (Node.js 10 is not present in Travis CI jobs, so this issue had not been noticed)
```
TypeError: Cannot read property 'status' of undefined
      at Test._assertStatus (node_modules/supertest/lib/test.js:229:11)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1667:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

Probably because along the way, in the `at Server.assert (node_modules/supertest/lib/test.js:127:12)` frame, an error
```
Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketOnEnd (_http_client.js:416:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
happens, that doesn't get processed and assertions run anyway and eventually `response.status` with `response` being `undefined` gives way.

Which in turn seems to be caused by any 1xx status except for 101 (currently 102 is used). Node.js 9 and prior don't have this issue.

Investigating into socket hanging up might be an overkill for the purposes of testing coloring in this logging library. So how about changing status code in this particular test to 101?

**Comment by dougwilson** [comment]
102 is a valid response code, I would rather not change it. Why does it work on every prior Node.js line but not 10? Is this an intended change in Node.js 10 or an accidental new bug in Node.js 10 that our test suite revealed? If it is an intentional change in Node.js 10, can you paste the changelog entry from Node.js 10 that states this?

I need concrete evidence this is not a Node.js bug before I'm simply going to change it. That would be a disservice to the Node.js community to notice a bug in a new major and simply ignore it.

**Comment by st-sloth** [comment]
[The changelog for 10.0.0](https://nodejs.org/en/blog/release/v10.0.0/) contains
> Processing of HTTP Status codes `100`, `102-199` has been improved. [[baf8495078](https://github.com/nodejs/node/commit/baf8495078)].

However, I am not versed well enough in lifecycles of HTTP connections to see whether the observed behavior here is valid according to the spec and new changes and to decide what are our next actions.

Just in case, I made [a simple test](https://github.com/st-sloth/node-socket-hanging/blob/master/test/http.js) to showcase the issue outside of `morgan` codebase. [The result for Node.js 9](https://travis-ci.org/st-sloth/node-socket-hanging/jobs/403975781) and [for Node.js 10](https://travis-ci.org/st-sloth/node-socket-hanging/jobs/403975782).

**Comment by dougwilson** [comment]
Sorry I forgot about this issue. So the issue is that writing a HTTP 1xx code to a HTTP response doesn't end the response, so getting an end in an error. The HTTP server in Node.js doesn't prevent this condition at all, so `morgan` was made to do something sane when this happens. In this particular case, the HTTP server in 10.x still let's this happen, but the HTTP client now treats it as if it's a HTTP framing error (which it is) and the HTTP client will destroy the socket, giving us that error.
