### ISSUE TITLE
what is the reason this is named after dexter?

### ISSUE THREAD

**Issue by bruce-solar** [expressjs/morgan#192]
i watched dexter to completion and agree that was a mistake. they lost their way. but i think it is a serious shortcoming of the readme not to include a short backstory on why the morgan package is named after dexter.

if you tell me i'll generate a PR updating the readme or add an explanatory document.

**Comment by dougwilson** [comment]
The original author who named the module is no longer active here, so no idea. I've never watched the show, either.

**Comment by bmacnaughton** [comment]
thanks. feel free to close this if you'd like. or leave it open to see what answers we might get.

**Comment by dougwilson** [comment]
I'm kind of curious what you think if you're willing. I don't mind spoilers or anything, generally curious now :D

**Comment by bmacnaughton** [comment]
i'm kind of hoping that @Fishrock123 will jump in (it was his commit that added the readme but he might just have been documenting a decision). my guesses are kind of contrived, i.e., i would never have guessed it if i hadn't seen the sentence.

dexter morgan was a "blood-spatter expert" that happened to be a serial killer. but he only killed bad serial killers, so i guess that made him kind of a good serial killer, as much as possible.

but here's my tortured logic. morgan kind of creates a lot of blood spatter that allows a forensic specialist, like dexter, to painstakingly reassemble the crime. so if a developer is analogous to dexter then morgan creates the data that dexter uses to solve crimes (bugs, in this case).

it's kind of tortured because morgan creates the blood spatter, so-to-speak while in the show morgan only interpreted the blood spatter (well, he created his own spatter too but he didn't need to interpret that). but it's the best i can do.

**Comment by dougwilson** [comment]
Closing due to no follow up, so no need to keep it open indefinitely :)
