### ISSUE TITLE
Skip logging query paramters

### ISSUE THREAD

**Issue by Domuska** [expressjs/morgan#204]
Hello! Thanks for the awesome library!

Is it possible to skip logging query parameters for requests? I'd like to log the route that requests get into, but I don't want to have the query parameters logged.

Thanks!

**Comment by dougwilson** [comment]
Hi @Domuska ! Most likely your log format is using the `:url` token (https://github.com/expressjs/morgan#url) which is the full URL as Node.js / Express sees it. This includes the query string.

It sounds like you only want to log the path name part of the URL. If you are using Express, this is exposed automatically as `req.pathname`.

Provided this, there are two different ways you can log path name instead of URL in your morgan logs

1. Create a new token (https://github.com/expressjs/morgan#creating-new-tokens) like `:pathname` and then use that in your log format. For example `morgan.token('pathname', (req, res) => req.pathname)`.
2. Redefine the existing `:url` token if you never want the full URL. For example `morgan.token('url', (req, res) => req.pathname)`.

I hope this helps!

**Comment by Domuska** [comment]
Ah, right, for some reason I didn't realize I could create just a new token to do this. Thanks a bunch!
