### ISSUE TITLE
Discuss: morgan@2.0.0

### ISSUE THREAD

**Issue by ryhinchey** [expressjs/morgan#222]
Opening this to start a discussion about if a v2 of morgan would be considered and what the goals of it would be.  

As someone who would be happy to contribute to the effort, I wanted to gauge interest and come up with ideas of what a v2 would be looking to accomplish.

**Some issues I think are relevant for a v2:**
- https://github.com/expressjs/morgan/issues/190 - officially remove `morgan.default`
- https://github.com/expressjs/morgan/issues/142 & https://github.com/expressjs/morgan/issues/141 - finding an alternative to adding values to the `req` and `res` objects or coming up with a safer naming convention as to not conflict with other middleware

**Some ideas:**
- ~~removing the `compile` function. the `compile` can be difficult to understand and uses what some consider to be an [unsafe technique] - (https://github.com/expressjs/morgan/blob/master/index.js#L3910)~~ - https://github.com/expressjs/morgan/issues/223 closed due to convincing by Doug that compile is valuable to users
- ~~replacing the `token` syntax with functions. Using a function is [already documented](https://github.com/expressjs/morgan#use-custom-token-formats) and if `compile` is removed, we'd need to move all tokens to plain functions.~~ - if compile stays, we need token syntax

**Comment by dougwilson** [comment]
> removing the compile function. the compile can be difficult to understand and uses what some consider to be an unsafe technique

I've never heard this proposal before, but would love to hear more about it. What would someone who is making use of that feature do without it? Is there an alternative proposed here? I ask because ideally we want to improve the module, and if there is an alternative and we can put it into the 1.x line and deprecate the old functions _prior_ to suddenly dropping, that would be the most ideal path.

**Comment by dougwilson** [comment]
> replacing the token syntax with functions. Using a function is already documented and if compile is removed, we'd need to move all tokens to plain functions.

I'm a little unclear on this proposal as well. All tokens are already functions. So by changing them to functions it's not clear what that would look like since they are functions today...

I think this thread is about to become very messy. Should we make a separate issue for each separate proposal so the discussions do not end up mixed together? I feel like this should just be a meta issue for _existing_ proposal we can link to and the discussion here should be on if they should be in the release vs making multiple new proposals in a single issue that would then need to be cross discussed.

Thoughts?

**Comment by ryhinchey** [comment]
I think that's a great idea.  I'll open separate issues with proposals and more detail

**Comment by dougwilson** [comment]
Nice! And to be clear: I suggest this because I _want_ to have these discussions and hear your thoughts and have you working on this :rocket:

**Comment by Divlo** [comment]
Yes, still the warning when using es6 import in node : morgan deprecated default format: use combined format. Could be cool to fix that! :)
