### ISSUE TITLE
Usage in ES6 promise based import does not work

### ISSUE THREAD

**Issue by harisrahman** [expressjs/morgan#256]
What i am trying to do is to import and use morgan only in development environment. Morgan is only a dev dependency, in my project so cannot even import morgan in other environments.

```
if (process.env.NODE_ENV === 'development')
{
	import('morgan').then((morgan) => {
		app.use(morgan.default("dev"));
	});
}

``` 

Morgan stops logging completely, when this type of import is done.

**Comment by dougwilson** [comment]
This is unrelated to morgan, but due to the async nature of import vs sync of require.

By the time the promise resolves, you have probably added all your routes so app.use is not called last instead of the physical position in the file.

You will have to manage this async nature in your app somehow.
