### ISSUE TITLE
Security Vulnerability in debug 2.6.9

### ISSUE THREAD

**Issue by Kurt-von-Laven** [expressjs/morgan#275]
[morgan pins debug to 2.6.9](https://github.com/expressjs/morgan/blob/19a6aa5369220b522e9dac007975ee66b1c38283/package.json#L19). [The issue](https://github.com/advisories/GHSA-9vvw-cc9w-f27h) may be addressed by upgrading debug to 3.1.0 or greater.

**Comment by dougwilson** [comment]
Hello, and thank you for your report. The redos fix for the issue you linked was backported to debug 2.6.9 which is what we are already using. This was done by the debug project by my request back in 2017, when the fix came out: https://github.com/debug-js/debug/pull/504#issuecomment-331449019 . I took a look at your link and under references it links to that Github PR I liked above where the project states the fix is also in 2.6.9.

If you are using an automated scanning tool that is incorrectly reporting 2.9.6 as vulnerable, you will need to report this to the tool you are using.
