### ISSUE TITLE
how to log response message?

### ISSUE THREAD

**Issue by soundyogi** [expressjs/morgan#32]
Hi!

Given this code:

``` javascript
    .get('/test', function(req,res){
      res.status(200).json({message:'everything ok'})
    })
```

How can I log the message with morgan?

``` javascript
morgan.token('json', function(req, res){ return res.body; })
app.use(morgan(':method :url :status :response-time ms - :res[content-length] :json'))
```

res.body is empty ?_?

I am trying for hours now, sorry if this is a stupid question.

**Comment by richburdon** [comment]
It's often quite useful to log (to the console) JSON responses on the server. Can anyone share if they were able to use morgan for this purpose?

**Comment by faisal3389** [comment]
@soundyogi can you share how you managed to get the response data.

**Comment by faisal3389** [comment]
@soundyogi can you share how you managed to get the response data.

**Comment by pleerock** [comment]
@dougwilson I think its good to add such option and let user to decide if he wants log body or not. Modern tools like graphql use a single endpoint `/graphql` and send actual queries in a request body. It makes zero point to use morgan with graphql since all logs are the same - `/graphql` and you have no idea what query was actually executed.
