### ISSUE TITLE
how do I change the default timezone?

### ISSUE THREAD

**Issue by smilence86** [expressjs/morgan#66]
I found the default timezone is "+0000" in output log on my servers, How do I change the timezone? 
example, change to: 02/Jun/2015:08:06:14 +0300 
who know it?  please help me, thanks~

**Comment by chk-** [comment]
I just came across the same issue.
@dougwilson wrote in issue https://github.com/expressjs/morgan/issues/21 -> https://github.com/expressjs/morgan/issues/13 "...all logs are in UTC because it is an absolute standard."
I don't think so and found Wikipedia - Common_Log_Format and others.
However, a workaround was also posted at #13 (new Date().toString()) But the output is not the clfdate format!
In principle there is the possibility to use a custom token for that. I show my personal solution:
```javascript
morgan.token('date', function() {
	var p = new Date().toString().replace(/[A-Z]{3}\+/,'+').split(/ /);
	return( p[2]+'/'+p[1]+'/'+p[3]+':'+p[4]+' '+p[5] );
});
```

**Comment by dougwilson** [comment]
Yes, defining a custom token is the way to change it (which is why you can define tokens).

**Comment by smilence86** [comment]
Okay, thanks~ I have resolved.

**Comment by zhanbei** [comment]
Is the `:date[clf]` supposed to use server timezone like the `-0700` in `[10/Oct/2000:13:55:36 -0700]` from [Wikipedia - Common_Log_Format](https://en.wikipedia.org/wiki/Common_Log_Format)? 

It seems to be *yes*, which I do think should be stated in the `README.md` file to make it clear.

What do you think? Thanks.
