### ISSUE TITLE
Does 'response-time' include time to send response to client?

### ISSUE THREAD

**Issue by STRML** [expressjs/morgan#67]
While the documentation says this about `response-time`:

> The time between the request coming into morgan and when the response headers are written, in milliseconds.

We have noticed that latent / far away clients record higher response times than closer ones, making this number difficult to use for any sort of performance monitoring. 

It appears that the module `on-finished` only calls back when the response has been completely written, acked and closed.

Am I correct on this? If so, would it make sense to write a PR to either fix `response-time` or add another token that ignores client latency?

**Comment by dougwilson** [comment]
Interesting. Sadly this is how `mogran` has operated since it was first written: https://github.com/expressjs/morgan/commit/79622119370961349101f676965987320013835b which means at least right now, it's a documentation issue (where the docs are just wrong).

We cannot actually change the timing of the firing without releasing a major (which is restricted until August).

The fix doesn't require behavior to be altered (i.e. the timing of the log writing does not need to be altered), and I'll try to get to it this weekend if someone doesn't get to it first. It boils down to tracking the event properly and storing the value somewhere; a fix really needs to happen to the `:date` token as well.

**Comment by STRML** [comment]
How about a new token, like `response-time-internal`? It would get around the major release issue. I think that both numbers are useful.

**Comment by dougwilson** [comment]
The major version bump was in reference to changing the timing of the log firing :) The actual fix for this can be done with a minor to be safe (but really could be a patch version, technically).
