### ISSUE TITLE
http return status code ： - - ,why？

### ISSUE THREAD

**Issue by chelsh** [expressjs/morgan#77]
![image](https://cloud.githubusercontent.com/assets/10752360/9159431/39eb66ca-3f5b-11e5-8eba-ea238a21e47a.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9159437/44f02402-3f5b-11e5-8e53-391316e8c2f3.png)

**Comment by chelsh** [comment]
"name": "express",
  "description": "Fast, unopinionated, minimalist web framework",
  "version": "4.12.3",

**Comment by dougwilson** [comment]
Hi! In order to answer that, can you start with how you are calling the morgan() function in your code?

**Comment by dougwilson** [comment]
Another this you can try is to validate that a response was actually sent to the client. The status will appear as "-" if a response was never sent to the user, for example, the TCP socket closed prior to writing the response.

**Comment by chelsh** [comment]
i use the frame:kraken-js,which is provided by paypal.kraken-js use express v4.12.3 and morgan v1.6.0

**Comment by chelsh** [comment]
code:
morgan.format('combined', ':remote-addr - :remote-user [:date[clf]] ":method :url HTTP/:http-version" :status :res[content-length] ":referrer" ":user-agent"')

**Comment by dougwilson** [comment]
Thanks! Can try  to validate that a response was actually sent to the client? The status will appear as "-" if a response was never sent to the user (and is perfectly valid), for example, the TCP socket closed prior to writing the response. You can use tools like Wireshark to determine this.

Otherwise, there wont be much I can do without full, complete instructions on how to reproduce or if you provide a PR.

Remember, there are valid reasons it is "-", so just it being that isn't actually a bug.
