### ISSUE TITLE
got some encoding error when writing log into files

### ISSUE THREAD

**Issue by CocaCola183** [expressjs/morgan#80]
Node 0.12.7  
express ~4.13.1  
margon ^1.6.1  

Here is the code: 

```js
var logger = require('morgan');
var accessLogStream = fs.createWriteStream(__dirname + '/access.log', {flags: 'a', encoding: 'utf8'});
app.use(logger('dev', {stream: accessLogStream}));
```

But I got access.log like this:  
![2015-09-08 8 04 19](https://cloud.githubusercontent.com/assets/8912876/9734364/fabc4110-5664-11e5-867e-e61055796f02.png)

Maybe I made some mistakes?

**Comment by dougwilson** [comment]
Hi! This is expected, because the "dev" format is colored. If you were to view that file with a color-aware viewer, those characters would not be displayed.

If you are not intending to view it in a color-aware viewer, then you will need to use a non-colored format, or define your own format (dev is the only format that is colored; only intended to be output directly to your console).

**Comment by CocaCola183** [comment]
@dougwilson Thanks for your help

**Comment by dougwilson** [comment]
No problem!
