### ISSUE TITLE
Some log entries seem to be missing

### ISSUE THREAD

**Issue by Redsandro** [expressjs/morgan#99]
I am logging session data in a database so I know that certain visits occured. However, when grepping through access logs, it seems that 1% of entries are missing, even though `morgan` is the first line if code in the path that results in a session log.

Any ideas as to what could be causing this?

```js
var stream = require('logrotate-stream');
var morgan = require('morgan');
var app = require('express')();
```

...

```js
var fsAccessLog	= stream({ file: path.join(config.log.path, config.log['access']), size: '50m', keep: 9, compress: true});
var logReq = ':date[iso] [:remote-addr] REQ ":method :url HTTP/:http-version" ":referrer" ":user-agent"';
var logRes = ':date[iso] [:remote-addr] RES :url :status :response-time ms :res[content-length] bytes';

app.use(morgan(logReq, {stream: fsAccessLog, immediate: true}));
app.use(morgan(logRes, {stream: fsAccessLog, immediate: false}));
```

**Comment by dougwilson** [comment]
Weird, I've never heard of such a problem. Have you tried removing the use of `logrotate-stream` to see if that stream is causing the issue? I found an old PR https://github.com/dstokes/logrotate-stream/pull/4 that sounds like it could be an issue, but you could already have the fix (but if there was an issue like that before, there could be another in that module).

Otherwise, without instructions for how I can reproduce the issue, I may have to lean on you to debug it and let me know your findings.

**Comment by Redsandro** [comment]
Thanks for the quick response. I am at 2.4, this pr was labelled as 2.5, so chronologically speaking it could be relevant.

Not sure this is the cause as conflicting writes should either pick the request (instant) log or the response (non-instant), but I will update the module and watch this a bit more to see if I notice more missing entries.

If that happens, I could forego the `logrotates` module, but then I need to find a solution for the problem that caused me to start using the module in the first place. ;)

**Comment by dougwilson** [comment]
Hi @Redsandro, I'm going to close this issue since I haven't heard anything back after you went to try updating that module.

Unfortunately I cannot reproduce and there is just not enough information here for me to figure it out. Since you can reproduce, you are in the key position to attach a debugger to diagnose the issue and come up with a solution. If you are looking for us to debug the issue, we need all of the following to proceed:

1. The version of Node.js you are using.
2. The version of this module you are using.
3. Provide complete server-side code that reproduces the issue. It must be self-contained such that I can copy and paste the code into a file and run it to have a server that reproduces the issue. Please use as few other modules besides this one as possible in order to reproduce the issue, as the more there are, the harder it is going to be to diagnose.
4. Provide the exact steps needed to reproduce the issue. For example, this may be a `cURL` or similar command to make to the server provided in number 3. Explain what we will see when we hit the issue and what we should see if the issue wasn't there.

**Comment by Redsandro** [comment]
Hi @dougwilson sorry for not getting back to you earlier.
I haven't actively noticed this problem since. The issue was not structural, and we can't be sure what ingredients needed to be in the mix to cause this. We've upgraded servers and a lot of packages, perhaps the issue is fixed.

We are still actively using morgan in the same way, so I will revisit this issue when I notice a reprise of this problem.
